### PR TITLE
Add rules for git gutter scopes

### PR DESCRIPTION
**Pull request by lamartire**
Useful thing in my opinion.

### CODE REVIEW

**Comment by tonsky** [comment]
Why git_gutter specifically? generic markup.* would work just fine (and I have some of them, maybe not all)

**Comment by lamartire** [comment]
In my case it is not works, all glyphs are black. In the mini-map same situation.
This request works fine.

**Comment by tonsky** [comment]
which theme are you using? Alabaster or BG?

**Comment by lamartire** [comment]
Just Alabaster.

**Comment by tonsky** [comment]
Try 1.4.0. Should be fixed now

**Comment by lamartire** [comment]
Thank you 🙌

**Pull request closed without merging**
